In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
#https://jalammar.github.io/visual-numpy/

In [4]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array.max()

np.int64(40)

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
 ##array arithmetic 

In [12]:
my_list1 = [1,2]

In [19]:
my_list2 = [2,3]

In [20]:
my_list1 + my_list2

[1, 2, 2, 3]

In [21]:
my_numpy_array1 = np.array(my_list1)

In [22]:
my_numpy_array2 = np.array(my_list2)

In [23]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [24]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [25]:
my_numpy_array1 *5

array([ 5, 10])

In [26]:
my_list1*5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [27]:
other_array = np.array([10,20,30,40,50])

In [28]:
other_array.sum()

np.int64(150)

In [29]:
my_numpy_array1

array([1, 2])

In [30]:
other_array

array([10, 20, 30, 40, 50])

In [31]:
##indekslere bakacağız

In [32]:
#arange & indexing

In [33]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [36]:
np_array_new = np.arange(0,10)

In [37]:
np_array_new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np_array_new[0]

np.int64(0)

In [40]:
np_array_new[1]

np.int64(1)

In [41]:
np_array_new[-1]

np.int64(9)

In [42]:
np_array_new[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np_array_new[:-1:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
np_array_new[1:4:]

array([1, 2, 3])

In [45]:
np_array_new[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [46]:
np_array_new[2:6:2]

array([2, 4])

In [47]:
#random

In [48]:
np.random.randn(4)

array([-0.8973646 , -0.58062881,  1.81576641,  0.79733461])

In [49]:
np.random.rand(4,4)

array([[0.30059144, 0.50611357, 0.36120014, 0.56128437],
       [0.52071417, 0.59695198, 0.40087493, 0.71811699],
       [0.98382137, 0.54949945, 0.37248203, 0.93926011],
       [0.77830561, 0.12749872, 0.24884488, 0.0431648 ]])

In [50]:
np.random.randint(1,300,5)

array([129,  67,  55, 168,  54])

NUMPYDA MATRİSLERE GİRİŞ

In [51]:
my_matrix = [[5,10],[15,20]]

In [52]:
my_matrix[0]

[5, 10]

In [54]:
#row * column

In [55]:
#satır ve sütun sayısı , sırasıyla

In [56]:
numpy_matrix = np.array([[5,10],[15,20]])

In [57]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [58]:
numpy_matrix.sum()

np.int64(50)

In [59]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.random.random((3,2))

MATRİX ARİTMETİĞİ

In [61]:
first_array = np.array([[10,20],[30,40]])

In [62]:
second_array = np.array([[5,15],[25,35]])

In [63]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [64]:
third_array = np.array([[50,60]])

In [65]:
third_array

array([[50, 60]])

In [66]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [67]:
third_array = np.array([[10],[20]])

In [68]:
third_array

array([[10],
       [20]])

In [69]:
first_array + third_array

array([[20, 30],
       [50, 60]])

matrix multiplication


In [73]:
#dot product -- gercek matris carpmasi

In [74]:
first_matrix = np.array([[10,20,30]])


In [75]:
first_matrix

array([[10, 20, 30]])

In [76]:
second_matrix = np.array([[2,3],[2,3],[2,3]])


In [77]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [78]:
first_matrix.shape

(1, 3)

In [79]:
second_matrix.shape

(3, 2)

In [80]:
result_matrix = first_matrix.dot(second_matrix)


In [81]:
result_matrix

array([[120, 180]])

In [82]:
result_matrix.shape

(1, 2)

GERÇEK HAYAT ÖRNEKLERİ

In [83]:
new_array = np.random.randint(1,100,20)


In [84]:
new_array

array([65, 59, 90, 67, 77, 54, 72, 24, 42, 81, 11, 21, 69,  3, 85,  6, 68,
       24, 32, 23])

In [85]:
new_array>25

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False, False,  True, False,  True, False,  True, False,
        True, False])

In [ ]:
new_array[new_array > 25

In [ ]:
#transpoze işlemleri

array([65, 59, 90, 67, 77, 54, 72, 42, 81, 69, 85, 68, 32])

In [87]:
matrix_array = np.array([[10,20],[20,30],[30,40]])


In [88]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [89]:
matrix_array.transpose()


array([[10, 20, 30],
       [20, 30, 40]])

In [90]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [91]:
random_array = np.random.random((6,1))


In [92]:
random_array

array([[0.20570248],
       [0.93865636],
       [0.23292725],
       [0.94775971],
       [0.61779365],
       [0.03099849]])

In [93]:
random_array.reshape(2,3)


array([[0.20570248, 0.93865636, 0.23292725],
       [0.94775971, 0.61779365, 0.03099849]])

In [94]:
random_array.reshape(3,2)


array([[0.20570248, 0.93865636],
       [0.23292725, 0.94775971],
       [0.61779365, 0.03099849]])

REAL LIFE CASES

In [95]:
data = np.array([10,12,13,15,18,25,100,105])

In [96]:
#compute z-scores
#first we find our data's mean

In [97]:
mean = np.mean(data)

In [98]:
mean

np.float64(37.25)

In [99]:
#standart sapmasını bulalım verinin ortalama etrafında ne kadar yayıldığını ölçer

In [100]:
std = np.std(data)

In [101]:
std

np.float64(37.9333296719389)

In [102]:
#şimdi z score bulalım
z_scores = (data - mean) / std

In [103]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [104]:
np.abs(z_scores) > 1

array([False, False, False, False, False, False,  True,  True])

In [105]:
outliers = data[np.abs(z_scores) > 1]

In [106]:
outliers

array([100, 105])

In [ ]:
#abs ile negatif değerler mutlak deegere dönüştürüüyor.uç değerler de > 1 olanlar olmus olyuyor.


In [107]:
##math equations

In [108]:
# Solve 2x + 3y = 8 and 5x + 7y = 19


In [109]:
#önce coefficientları yazarız yani 2,3,5,7 yi felan.

In [110]:
A = np.array([[2,3],[5,7]])

In [111]:
#constant matris

In [112]:
b = np.array([8,19])

In [113]:
#solve for x and y

In [114]:
solution = np.linalg.solve(A,b)

In [115]:
solution

array([1., 2.])